# Generated by Django 5.2.8 on 2025-11-24 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dziecko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('data_urodzenia', models.DateField()),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1)),
                ('pesel_matki', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='APGARScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pomiaru', models.DateTimeField(auto_now_add=True)),
                ('apgar_1min', models.IntegerField(help_text='Wynik po 1 minucie')),
                ('apgar_5min', models.IntegerField(help_text='Wynik po 5 minutach')),
                ('apgar_10min', models.IntegerField(blank=True, null=True)),
                ('lekarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dziecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apgar', to='neonatology.dziecko')),
            ],
        ),
        migrations.CreateModel(
            name='ParametryZewnetrzne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pomiaru', models.DateTimeField(auto_now_add=True)),
                ('wzrost_cm', models.FloatField()),
                ('waga_kg', models.FloatField()),
                ('czy_wczesniak', models.BooleanField(default=False)),
                ('obwod_glowy_cm', models.FloatField()),
                ('oddechy_na_min', models.IntegerField()),
                ('natlenienie_spO2', models.IntegerField()),
                ('dziecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametry', to='neonatology.dziecko')),
                ('lekarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
