# Generated by Django 5.2.8 on 2025-12-09 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonatology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dziecko',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
