# Generated by Django 5.2.8 on 2026-01-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonatology', '0002_dziecko_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('grupa_krwi', models.CharField(blank=True, max_length=5)),
                ('konflikt_serologiczny', models.BooleanField(default=False, help_text='Czy występuje konflikt serologiczny (np. Rh)')),
            ],
        ),
        migrations.RemoveField(
            model_name='dziecko',
            name='pesel_matki',
        ),
        migrations.AddField(
            model_name='dziecko',
            name='matka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dzieci', to='neonatology.matka'),
        ),
    ]
