# Generated by Django 5.2.8 on 2026-01-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonatology', '0004_historicalapgarscore_historicalparametryzewnetrzne'),
    ]

    operations = [
        migrations.AddField(
            model_name='dziecko',
            name='grupa_krwi',
            field=models.CharField(blank=True, help_text='Grupa krwi dziecka (np. A+, B-, 0+)', max_length=5),
        ),
    ]
